### ISSUE TITLE
Introduction to the tools

### ISSUE THREAD

**Issue by ahovgaard** [ahovgaard/TiPL-kleenex-approx#11]

**Comment by Lundbrik** [comment]
I have added some finishing touches to this. I can't think of anything else to put here. Do you guys think it's alright or do you have anything to add?

**Comment by ahovgaard** [comment]
Sorry we've been busy with PFP, but hopefully that is basically done now. I'll focus on TiPL for the next couple of days. I'll take at look at this too.

**Comment by ahovgaard** [comment]
I have tried to expand this a bit (4098ee3).
