### ISSUE TITLE
experiment with NR-grep

### ISSUE THREAD

**Issue by Ginko-X** [ahovgaard/TiPL-kleenex-approx#16]
in section 3.3.1, I read the remarks about NR-grep, says its weird performance. 
Is it that  the time  shown in Figure 7 is the running time as k grows? If so, I can explain that in the survey section for consistency.  
This is maybe because  NR-grep uses different algorithms for different patterns (length, k, and so on).

**Comment by Lundbrik** [comment]
Yes it is.
