### ISSUE TITLE
Run the benchmarks on a fast machine or Napoleon

### ISSUE THREAD

**Issue by ahovgaard** [ahovgaard/TiPL-kleenex-approx#4]

**Comment by Lundbrik** [comment]
Do you have anything to add to the results chapter? I can't really think of anything else to write (at least right now) other than maybe mentioning that we did a few other experiments that didn't really show anything different.

**Comment by ahovgaard** [comment]
What did the other experiments show? I'm not sure I've really looked at them. Just very similar to all the others?

**Comment by Lundbrik** [comment]
I think it is only the increasing length ones and repetitions, which seem to be very similar to the short and long experiments
