### ISSUE TITLE
Finish the benchmark scripts

### ISSUE THREAD

**Issue by ahovgaard** [ahovgaard/TiPL-kleenex-approx#6]

**Comment by ahovgaard** [comment]
Can scan_for_matches do repetitions like: ?
```
/GGGTGC/<2>{10,50}
```
I can't really seem to find an option for this.

**Comment by ahovgaard** [comment]
Also, is this not supported?
```
(GCCCAGAGA|ACTTTCAGGA)[1,0,0]
```
I get something like:
```
failed to parse pattern: (GCCCAGAGA|ACTTTCAGGA)[1,0,0] 
Command exited with non-zero status 1
```

**Comment by Ginko-X** [comment]
/GGGTGC/<2>{10,50} may be equivalent to : 
```
p1=GGGTGC[2,0,0]  p1[2,0,0] p1[2,0,0] ... (repeat 10 times)
p2=GGGTGC[2,0,0]  p2[2,0,0] p2[2,0,0] ... (... 11) 
...
pn=GGGTGC[2,0,0]  pn[2,0,0] pn[2,0,0] ... (... 50) 

```
but seems doesn't support `p1[2,0,0] {10,50} `. 


And for this pattern, `(GCCCAGAGA|ACTTTCAGGA)[1,0,0]`, how about using `(GCCCAGAGA[1,0,0]|ACTTTCAGGA[1,0,0])` ?

**Comment by ahovgaard** [comment]
I think that would be unnecessary backreferencing, although sfm may be able to figure out that `p1` is not a range of variable symbols. What does the multiple lines mean? Is it really the same as the repetitions?

**Comment by ahovgaard** [comment]
It seems that kleenex actually does not find overlapping matches. I tried searching for the pattern /ABCABC/ in the text "ABCABCABC" and it just finds one match.

**Comment by ahovgaard** [comment]
Do you know what the `?:` does in the expression `(?:TGCAAGCGTTAAT){s<=2}` ? I can't really figure out what difference it makes and I can't find proper documentation for it.

**Comment by ahovgaard** [comment]
`(?: ...)` is a non-capturing group. For the standard `re` module, it says that there's no performance difference (https://docs.python.org/2/howto/regex.html#non-capturing-and-named-groups).

**Comment by ahovgaard** [comment]
This is probably done now.
