### ISSUE TITLE
Write an introduction

### ISSUE THREAD

**Issue by ahovgaard** [ahovgaard/TiPL-kleenex-approx#7]

**Comment by ahovgaard** [comment]
I'm working on a draft of some sort.

**Comment by ahovgaard** [comment]
250aed4: Please do take a look at it and correct things you don't agree with.

**Comment by Ginko-X** [comment]
have read it. It's nice  👍

**Comment by Lundbrik** [comment]
Looks good.

**Comment by Lundbrik** [comment]
I guess this is done
