### ISSUE TITLE
Write about experiment setup (machine etc.)

### ISSUE THREAD

**Issue by ahovgaard** [ahovgaard/TiPL-kleenex-approx#9]

**Comment by Lundbrik** [comment]
Well I can report that the current template_long.txt cannot be compiled with a Hamming distance of 3, it simple used up all the RAM even on the GPU machine. Neither can alternation. Repetition failed even on k = 0, so I'm looking at modifying it untill it compiles

**Comment by ahovgaard** [comment]
That's crazy. I guess the only reason he was able to compile anything for `k=9` in the thesis is because it was a very short pattern like `/a*b/<k>`.

**Comment by Ginko-X** [comment]
I was also curious about how things will go on after k >9 when I reviewed the report. Well I'll say the guy is kind of ずるい（don't know the counterpart word in English）, he should know this problem but seems never made it explicit in the report ╮(￣▽￣)╭

**Comment by ahovgaard** [comment]
Just some thoughts about the problems with compilation time...

Peter argues that the running time for `k` errors is `O(nmk)` where `m` is the size of the transition relation of the kleenex program (not transformed). For regular Kleenex, it is `O(mn)` (Thm. 1 in POPL paper). However, also in the POPL paper, Thm. 2 says that for the oracle machine of size `m` (size of transition relation), there is an SST with `O(2^{m \log m})` states. But Peter's approximate kleenex transforms the NFST by splitting each nonterminal into `k` nonterminals and adding transitions for each possible error type and for each value up to `k`. So it appears to me that the SST size may also change to something like `O(2^{mk \log mk}`, since it is determinized from the transformed NFST. I suppose the simulation should still be `O(mnk)` though.
